version: "3"
services:
  kratos-migrate-cypress:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - kratos-sqlite-cypress:/var/lib/sqlite
      - type: bind
        source: ./ory_config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - cypress-test-network

  kratos-cypress:
    depends_on:
      - kratos-migrate-cypress
    image: oryd/kratos:v0.13.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - kratos-sqlite-cypress:/var/lib/sqlite
      - type: bind
        source: ./ory_config
        target: /etc/config/kratos
    networks:
      - cypress-test-network

  mailslurper-cypress:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - cypress-test-network

networks:
  cypress-test-network:
    driver: bridge

volumes:
  kratos-sqlite-cypress:
    driver: local